### PR TITLE
Removed RPX token

### PR DESCRIPTION
**Pull request by metachris**

### CODE REVIEW

**Comment by mhuggins** [comment]
This needs to be added to the blacklist in index.J's, otherwise the script will automatically re-add it to the json file.

**Comment by metachris** [comment]
Will do. Why is that?

**Comment by mhuggins** [comment]
The tokenList.json file is generated by the index.js script. That script is run nightly by CircleCI.

**Comment by mhuggins** [comment]
It runs nightly to ensure it's up to date.

**Comment by metachris** [comment]
oooh, got it, nice!

**Pull request closed without merging**
