### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by comountainclimber**
Adds SOUL's deprecated token hash to BLACKLIST object

### CODE REVIEW

**Comment by mhuggins** [comment]
CI run fixed the token JSON here: https://github.com/CityOfZion/neo-tokens/commit/37bea3d394ce0da72a024066136cb8469820a14c

**Comment by mhuggins** [comment]
Looks like NKN might need a similar fix.

**Comment by comountainclimber** [comment]
@mhuggins ci replaces the correct hash with the wrong one even with the blacklist in place... this is super frustrating haha

Can you help me just to just turn off this auto update feature?

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neo-tokens/pull/28

**Pull request merged**
