### PR TITLE
Update tokenList.json

### PR DESCRIPTION
**Pull request by comountainclimber**
Updates tokenList.json with the correct hash for SOUL

### CODE REVIEW

**Comment by mhuggins** [comment]
@comountainclimber This file gets autogenerated nightly, so your change will be overwritten as soon as CircleCI sees there's a difference.  I think the long-term fix would be to add "4b4f63919b9ecfd2483f0c72ff46ed31b5bbb7a4" to the `BLACKLIST` constant in `index.js`.

**Comment by comountainclimber** [comment]
@mhuggins do you know how the data here gets populated? notifications.neeeo.org/v1/tokens

**Comment by mhuggins** [comment]
I'm not sure, what's the issue with that endpoint?

**Comment by comountainclimber** [comment]
Well it’s returning the wrong hash for SOUL so I figured updating it at the source would just be the best fix

**Comment by mhuggins** [comment]
It includes both the "good" and "bad" token value.  Phantasma has two tokens, likely because they messed something up before their ICO and had to redo it.  I don't know the actual reason, but in any case, there are two script hashes.  If you search https://notifications.neeeo.org/v1/tokens for "SOUL", you'll see both scripthashes in there.  Just add the bad one to the `BLACKLIST` const, and problem solved.

**Comment by comountainclimber** [comment]
@mhuggins sorry was grepping that file from my phone but see that now... I will submit a PR to add the deprecated hash to the blacklist const thanks man

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neo-tokens/pull/27

**Comment by localhuman** [comment]
Just an FYI, the notificationsX.neeeo.org servers will be going away soon.  They are replaced by https://n1.cityofzion.io/ ( n1-n5)

**Comment by mhuggins** [comment]
Thanks @localhuman, looks like a 1:1 change here to use https://n1.cityofzion.io/v1/tokens.

**Pull request merged**
